{ config, pkgs, emacs-lsp-booster, lib, ... }:
  let
    custom-agda = pkgs.agda.withPackages
      [ pkgs.agdaPackages.standard-library ];

    usbeehive = pkgs.rustPlatform.buildRustPackage rec {
      pname = "usbeehive";
      version = "0.11.0";
      src = pkgs.fetchFromGitHub {
        owner = "abrauchli";
        repo = "usbeehive";
        rev = "v${version}";
        hash = "sha256-5aqEqt0zwzG4O+roq0p4vs59z7s2ERPE+FzyW9waegw=";
      };
      cargoHash = "sha256-YX72/E1N59U6EU54SWpL8Ew/eMelAjnBF7xqpLYCNIo=";
      buildInputs = [ pkgs.udev ];
      nativeBuildInputs = [ pkgs.pkg-config ];
      buildNoDefaultFeatures = true;
      buildFeatures = [ "cli" "dbus" "sysfs" "watch" ];
    };

    repoRoot = ../..;

    # List files under dir, skipping paths (or prefixes) in exclude.
    walk = dir: exclude:
      let
        go = d: prefix:
          let entries = builtins.readDir d;
          in lib.concatMap
            (name:
              let rel = if prefix == "" then name else "${prefix}/${name}";
              in
              if lib.elem rel exclude then []
              else if entries.${name} == "directory" then go (d + "/${name}") rel
              else [ rel ])
            (builtins.attrNames entries);
      in go dir "";

    # Symlink every file under repoDir (minus exclude) from liveDir.
    linkTree = { link, repoDir, liveDir, exclude ? [], keyPrefix ? "" }:
      lib.listToAttrs (map
        (rel: lib.nameValuePair (if keyPrefix == "" then rel else "${keyPrefix}/${rel}")
          { source = link "${liveDir}/${rel}"; })
        (walk repoDir exclude));

    # "# EXTEND <name>" markers splice in each extraDirs/<name>.ini in order --
    # works around Vale's config format having no include directive. Without
    # any extraDirs, markers just drop out, so casual.ini generates standalone.
    # academic.ini reuses the same casual.ini base plus its own extra layer,
    # so the two configs can't drift apart the way two independent files would.
    mergeValeIni = { base, extraDirs ? [] }:
      let
        markerPrefix = "# EXTEND ";
        resolveLine = line:
          if !(lib.hasPrefix markerPrefix line) then line
          else if extraDirs == [] then null
          else lib.concatMapStringsSep "\n"
            (extraDir: builtins.readFile (extraDir + "/${lib.removePrefix markerPrefix line}.ini"))
            extraDirs;
        lines = lib.splitString "\n" (builtins.readFile base);
        source = lib.concatStringsSep " + " ([ (baseNameOf base) ] ++ map baseNameOf extraDirs);
      in lib.concatStringsSep "\n" (
        [
          "# GENERATED by home-manager from ${source};"
          "# do not edit this file directly."
          ""
        ]
        ++ lib.filter (l: l != null) (map resolveLine lines)
      );

    valeCasualIni = mergeValeIni { base = ../vale/casual.ini; };
    valeAcademicIni = mergeValeIni { base = ../vale/casual.ini; extraDirs = [ ../vale/academic-extra ]; };
  in {
    # Home Manager needs a bit of information about you and the
    # paths it should manage.
    home.username = "bohdan";
    home.homeDirectory = "/home/bohdan";

    home.packages = with pkgs; [

      direnv
      nix-direnv # support direnv for flakes
      nixfmt # format nix files
      # nix-index # tool to find nixpkgs fields corresponding to paths
      nixd # language server for nix

      cachix # for better nix caches

      vale # for writing
      vale-ls # lsp server for vale
      texlab # lsp for latex

      nodejs # for github copilot
      emacs-lsp-booster # for lsp-booster

      haskellPackages.hasktags
      alex
      happy

      custom-agda
      #agda
      usbeehive

      pandoc
      librsvg # for rsvg-convert

      ripgrep
      fd
      jq

      diffpdf
      pdfsandwich
      tesseract

      tmux

      bash-language-server

      # TeX for AUCTeX preview-latex / texfrag inline math previews
      # (system ghostscript at /usr/bin/gs handles the PDF -> image step).
      (texlive.withPackages (ps: with ps; [
        scheme-basic # pdflatex and the core engine
        preview      # preview.sty
        mylatex      # mylatex.ltx, for preview-latex's preamble cache
        dvipng       # DVI -> PNG
        dvisvgm      # DVI/PDF -> SVG
        amsmath      # align, gather, ...
        amsfonts     # amssymb and friends
      ]))
    ];
    # This value determines the Home Manager release that your
    # configuration is compatible with. This helps avoid breakage
    # when a new Home Manager release introduces backwards
    # incompatible changes.
    #
    # You can update Home Manager without changing this value. See
    # the Home Manager release notes for a list of state version
    # changes in each release.
    home.stateVersion = "25.05";

    # Let Home Manager install and manage itself.
    programs.home-manager.enable = true;

    home.file = linkTree {
      link = config.lib.file.mkOutOfStoreSymlink;
      repoDir = repoRoot;
      liveDir = "${config.home.homeDirectory}/dotfiles";
      # not dotfiles to deploy: repo tooling, or (.config) handled separately
      exclude = [ ".config" ".git" ".claude" ".gitattributes" ".gitignore" "custom-settings.desktop" ];
    };

    xdg.configFile = let
      link = config.lib.file.mkOutOfStoreSymlink;
      dotfiles = "${config.home.homeDirectory}/dotfiles/.config";
    in
      linkTree {
        inherit link;
        repoDir = repoRoot + "/.config";
        liveDir = dotfiles;
        exclude = [
          "home-manager" # the flake itself
          "git" # not wired into home-manager yet
          "vale/academic-extra" # spliced into generated vale/*.ini below
          "vale/styles" # -> xdg.dataFile instead
          # emacs runtime state
          "emacs/elpa" "emacs/eln-cache" "emacs/tree-sitter" "emacs/var"
          "emacs/transient" "emacs/auto-save-list" "emacs/.cache" "emacs/projects"
        ];
      }
      // {
        "vale/.vale.ini".text = valeCasualIni;
        "vale/casual.ini".text = valeCasualIni;
        "vale/academic.ini".text = valeAcademicIni;
      };

    # StylesPath is one dir; custom styles must sit alongside vale-sync's packages.
    xdg.dataFile = linkTree {
      link = config.lib.file.mkOutOfStoreSymlink;
      repoDir = repoRoot + "/.config/vale/styles/AIWriting";
      liveDir = "${config.home.homeDirectory}/dotfiles/.config/vale/styles/AIWriting";
      keyPrefix = "vale/styles/AIWriting";
    };

    dconf.settings = {
      "org/gnome/Console" = {
        restore-window-size = true;
        last-window-size = lib.hm.gvariant.mkTuple [ 1000 700 ];
      };
    };

    # Don't use nix-provided man but rather host system one
    programs.man.enable = false;
    home.extraOutputsToInstall = [ "man" ];

    services.emacs = let
      sysEmacs = pkgs.runCommand "system-emacs" {} ''
        mkdir -p $out/bin
        ln -s /usr/bin/emacs $out/bin/emacs
        ln -s /usr/bin/emacsclient $out/bin/emacsclient
      '';
    in {
      enable = true;
      package = sysEmacs;
      # client.enable stays off — we already have our own emacsclient
      # desktop entries and don't want the module's duplicate.
      # Start only once the Wayland compositor is up and has imported
      # WAYLAND_DISPLAY etc. into the systemd user environment. Otherwise the
      # daemon races ahead with no display and emacsclient -c frames fail.
      startWithUserSession = "graphical";
    };

    # emacs-pgtk 30.2 crashes on graphical-frame teardown under Wayland with
    #   gdk_wayland_seat_get_wl_seat: assertion 'GDK_IS_WAYLAND_SEAT (seat)' failed
    # whenever DISPLAY is also set: GDK builds a stray X11 seat via Xwayland and
    # trips the assertion when a frame is closed, killing the whole daemon. Pin
    # the GTK backend to Wayland and drop DISPLAY so the daemon stays alive
    # across emacsclient -c open/close cycles. (Keys merge into the module's
    # Service section.)
    systemd.user.services.emacs.Service = {
      Environment = [ "GDK_BACKEND=wayland" ];
      UnsetEnvironment = [ "DISPLAY" ];
    };

    systemd.user.services.usbeehived = {
      Unit = {
        Description = "USBeehived D-Bus Daemon";
      };
      Service = {
        ExecStart = "${usbeehive}/bin/usbeehived";
        Restart = "on-failure";
      };
      Install = {
        WantedBy = [ "default.target" ];
      };
    };
  }
