{ config, pkgs, emacs-lsp-booster, lib, ... }:
  let
    custom-agda = pkgs.agda.withPackages
      [ pkgs.agdaPackages.standard-library ];

    repoRoot = ../..;

    # List files under dir, skipping paths (or prefixes) in exclude.
    walk = dir: exclude:
      let
        go = d: prefix:
          let entries = builtins.readDir d;
          in lib.concatMap
            (name:
              let rel = if prefix == "" then name else "${prefix}/${name}";
              in
              if lib.elem rel exclude then []
              else if entries.${name} == "directory" then go (d + "/${name}") rel
              else [ rel ])
            (builtins.attrNames entries);
      in go dir "";

    # Symlink every file under repoDir (minus exclude) from liveDir.
    linkTree = { link, repoDir, liveDir, exclude ? [], keyPrefix ? "" }:
      lib.listToAttrs (map
        (rel: lib.nameValuePair (if keyPrefix == "" then rel else "${keyPrefix}/${rel}")
          { source = link "${liveDir}/${rel}"; })
        (walk repoDir exclude));

    # "# EXTEND <name>" markers splice in extraDir/<name>.ini -- works around
    # Vale's config format having no include directive. Without an extraDir,
    # markers just drop out, so casual.ini/academic.ini generate standalone.
    mergeValeIni = { base, extraDir ? null }:
      let
        markerPrefix = "# EXTEND ";
        resolveLine = line:
          if !(lib.hasPrefix markerPrefix line) then line
          else if extraDir == null then null
          else builtins.readFile (extraDir + "/${lib.removePrefix markerPrefix line}.ini");
        lines = lib.splitString "\n" (builtins.readFile base);
        source = if extraDir == null then baseNameOf base else "${baseNameOf base} + ${baseNameOf extraDir}";
      in lib.concatStringsSep "\n" (
        [
          "# GENERATED by home-manager from ${source};"
          "# do not edit this file directly."
          ""
        ]
        ++ lib.filter (l: l != null) (map resolveLine lines)
      );

    valeCasualIni = mergeValeIni { base = ../vale/casual.ini; };
    valeAcademicIni = mergeValeIni { base = ../vale/academic.ini; };
  in {
    # Home Manager needs a bit of information about you and the
    # paths it should manage.
    home.username = "bohdan";
    home.homeDirectory = "/home/bohdan";

    home.packages = with pkgs; [

      direnv
      nix-direnv # support direnv for flakes
      nixfmt # format nix files
      # nix-index # tool to find nixpkgs fields corresponding to paths
      nixd # language server for nix

      cachix # for better nix caches

      vale # for writing
      vale-ls # lsp server for vale
      texlab # lsp for latex

      nodejs # for github copilot
      emacs-lsp-booster # for lsp-booster

      haskellPackages.hasktags
      alex
      happy

      custom-agda
      #agda

      pandoc
      librsvg # for rsvg-convert

      ripgrep
      fd
      jq

      diffpdf
      pdfsandwich
      tesseract

      tmux

      bash-language-server

      # TeX for AUCTeX preview-latex / texfrag inline math previews
      # (system ghostscript at /usr/bin/gs handles the PDF -> image step).
      (texlive.withPackages (ps: with ps; [
        scheme-basic # pdflatex and the core engine
        preview      # preview.sty
        mylatex      # mylatex.ltx, for preview-latex's preamble cache
        dvipng       # DVI -> PNG
        dvisvgm      # DVI/PDF -> SVG
        amsmath      # align, gather, ...
        amsfonts     # amssymb and friends
      ]))
    ];
    # This value determines the Home Manager release that your
    # configuration is compatible with. This helps avoid breakage
    # when a new Home Manager release introduces backwards
    # incompatible changes.
    #
    # You can update Home Manager without changing this value. See
    # the Home Manager release notes for a list of state version
    # changes in each release.
    home.stateVersion = "25.05";

    # Let Home Manager install and manage itself.
    programs.home-manager.enable = true;

    home.file = linkTree {
      link = config.lib.file.mkOutOfStoreSymlink;
      repoDir = repoRoot;
      liveDir = "${config.home.homeDirectory}/dotfiles";
      # not dotfiles to deploy: repo tooling, or (.config) handled separately
      exclude = [ ".config" ".git" ".claude" ".gitattributes" ".gitignore" "custom-settings.desktop" ];
    };

    xdg.configFile = let
      link = config.lib.file.mkOutOfStoreSymlink;
      dotfiles = "${config.home.homeDirectory}/dotfiles/.config";
    in
      linkTree {
        inherit link;
        repoDir = repoRoot + "/.config";
        liveDir = dotfiles;
        exclude = [
          "home-manager" # the flake itself
          "git" # not wired into home-manager yet
          "vale/styles" # -> xdg.dataFile instead
          # emacs runtime state
          "emacs/elpa" "emacs/eln-cache" "emacs/tree-sitter" "emacs/var"
          "emacs/transient" "emacs/auto-save-list" "emacs/.cache" "emacs/projects"
        ];
      }
      // {
        "vale/.vale.ini".text = valeCasualIni;
        "vale/casual.ini".text = valeCasualIni;
        "vale/academic.ini".text = valeAcademicIni;
      };

    # StylesPath is one dir; custom styles must sit alongside vale-sync's packages.
    xdg.dataFile = linkTree {
      link = config.lib.file.mkOutOfStoreSymlink;
      repoDir = repoRoot + "/.config/vale/styles/AIWriting";
      liveDir = "${config.home.homeDirectory}/dotfiles/.config/vale/styles/AIWriting";
      keyPrefix = "vale/styles/AIWriting";
    };

    dconf.settings = {
      "org/gnome/Console" = {
        restore-window-size = true;
        last-window-size = lib.hm.gvariant.mkTuple [ 1000 700 ];
      };
    };

    # Don't use nix-provided man but rather host system one
    programs.man.enable = false;
    home.extraOutputsToInstall = [ "man" ];
  }
