# Vale configuration.
#
# Vale's config format has no include directive, so each .ini is generated by
# splicing fragments into a shared base at the "# EXTEND <name>" markers. A
# profile declares which configs it wants and which of them ~/.config/vale/.vale.ini
# should be, so the two machines do not have to agree on either.
{ config, lib, dotfilesLib, ... }:
let
  cfg = config.dotfiles.vale;

  # "# EXTEND <name>" markers splice in each extraDirs/<name>.ini in order --
  # works around Vale's config format having no include directive. Without
  # any extraDirs, markers just drop out, so the base generates standalone.
  # Every config reuses the same base plus its own extra layer, so they can't
  # drift apart the way independent files would.
  mergeValeIni = { base, extraDirs ? [ ] }:
    let
      markerPrefix = "# EXTEND ";
      resolveLine = line:
        if !(lib.hasPrefix markerPrefix line) then line
        else if extraDirs == [ ] then null
        else lib.concatMapStringsSep "\n"
          (extraDir: builtins.readFile (extraDir + "/${lib.removePrefix markerPrefix line}.ini"))
          extraDirs;
      lines = lib.splitString "\n" (builtins.readFile base);
      source = lib.concatStringsSep " + " ([ (baseNameOf base) ] ++ map baseNameOf extraDirs);
    in lib.concatStringsSep "\n" (
      [
        "# GENERATED by home-manager from ${source};"
        "# do not edit this file directly."
        ""
      ]
      ++ lib.filter (l: l != null) (map resolveLine lines)
    );

  generated = lib.mapAttrs (_: extraDirs: mergeValeIni { inherit (cfg) base; inherit extraDirs; }) cfg.configs;
in {
  options.dotfiles.vale = {
    enable = lib.mkEnableOption "generated Vale configuration";

    base = lib.mkOption {
      type = lib.types.path;
      default = ../../vale/casual.ini;
      description = "The config every generated .ini layers its fragments onto.";
    };

    configs = lib.mkOption {
      type = lib.types.attrsOf (lib.types.listOf lib.types.path);
      default = { };
      example = lib.literalExpression ''{ casual = [ ]; academic = [ ../../vale/academic-extra ]; }'';
      description = ''
        Generated configs, as <name> -> fragment directories spliced into the
        base, in order. Each becomes ~/.config/vale/<name>.ini.
      '';
    };

    defaultConfig = lib.mkOption {
      type = lib.types.str;
      description = ''
        Which of `configs` ~/.config/vale/.vale.ini should be. Vale reads that
        file natively; the others are there for VALE_CONFIG_PATH.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [{
      assertion = cfg.configs ? ${cfg.defaultConfig};
      message = "dotfiles.vale.defaultConfig is '${cfg.defaultConfig}', which is not one of configs: "
                + lib.concatStringsSep ", " (lib.attrNames cfg.configs);
    }];

    dotfiles.configExcludes = [
      # Linked to StylesPath below instead of into ~/.config.
      "vale/styles"
      # The base is spliced into the generated configs; deploying it as well
      # would put the un-spliced source at the same path and win, because a
      # `source` from the blanket link beats this module's generated `text`.
      "vale/${baseNameOf cfg.base}"
    ];

    xdg.configFile =
      lib.mapAttrs' (name: text: lib.nameValuePair "vale/${name}.ini" { inherit text; }) generated
      // { "vale/.vale.ini".text = generated.${cfg.defaultConfig}; };

    # StylesPath is one directory, so custom styles have to sit alongside the
    # packages vale-sync downloads rather than in the repo's own tree.
    xdg.dataFile = dotfilesLib.linkTree {
      link = config.lib.file.mkOutOfStoreSymlink;
      repoDir = ../../vale/styles/AIWriting;
      liveDir = "${config.dotfiles.repoPath}/.config/vale/styles/AIWriting";
      keyPrefix = "vale/styles/AIWriting";
    };
  };
}
