Vocab = type-theory

MinAlertLevel = suggestion

Packages = Microsoft, \
proselint, \
write-good, \
https://github.com/Microflash/Prim/releases/latest/download/Prim.zip, \
Readability

# hedgeclipper removes parts of the sentence that sound apologetic or hedging
# Prim is rules-of-thumb for non-native speakers
# Readability is an automated metric calculation
